### ISSUE TITLE
How to set bitrate 

### ISSUE THREAD

**Issue by silent10** [louisyonge/opus_android#11]
How to set bitrate for encoding?

**Comment by silent10** [comment]
How can i set recording parameters sampling rate, bit rate and number of channels? Please reply.

**Comment by louisyonge** [comment]
OpusTool has many encoding parameters, including parameter for bitrate. Module "Oplayer" shows you how to set encoding/decoding parameters. OpusConverter.java holds all the API that you might need.

Recording has two steps, one is to capture the audio stream(WAV format) by AudioRecord, which is an Android system API. So AudioRecord should be configured as the way you wanted, sampling rate, bit rate, channels, etc. The second step is to convert the WAV stream to opus frame. Converting almost share the same characteristics as others.

Good luck. ^,^

**Comment by silent10** [comment]
So I successfully set sampling rate, bit rate and number of channels through JNI via opusTool.startRecording() in opusaudio.c. As libopus only support 8, 12, 16, 24 and 48 kHz sampling rate, I tried recording at these sampling rates with different bitrates and number of channels (1 and 2). Mono recording (1 channel) works for all bitrates in 8 ,12 and 16 kHz. Mono recording does not work for any bitrate in 24 and 48 kHz, the voice is running at these rates (see attachment). Stereo recording (2 channels) works for all bitrates in 12 and 16 kHz. Stereo recording does not work for any bitrate in 24 and 48 kHz, the voice is running at these rates too. Also, stereo recording at 8, 256 and 320 kbps in 8 kHz is corrupted. 

To make it work I changed the fileBuffer size from hardcoded value of 1920 to `(minBufferSize / 1920 + 1) * 1920` in OpusRecorder.java.

I think something needs to be changed in opusaudio.c or OpusRecorder.java to make the recording work at 24 kHz and 48 kHz. 

Can you help me on this please, I would be obliged. What could be wrong? Header size, frame size, something in page or some  other parameter?

I have attached a zip contataining 16kHz and 24kHz sample. 24 kHz has the running problem.
[opus128kbps.zip](https://github.com/louisyonge/opus_android/files/1212715/opus128kbps.zip)

If you are willing to help I can attach the complete project too.

**Comment by louisyonge** [comment]
@silent10 
Well, I must admit that I am not an expert on OPUS. I reason I made the project is simply that it is a home work assigned by a professor two years ago. ~~

Yes, recording haven't worked for some sample rates ever since the beginning of the project. There should be some constrains among  these parameters, but sadly, I am not a audio expert. Adjusting FileBuffer size in OpusRecorder.java is a good strategy, which was what I did two years ago.

If the WAV stream is well generated, then some codes of encoding in Native Level and in OpusRecord.java need to be changed. eg: In OpusTool.java
```
    /**
     * Writing audio frame to encoder
     *
     * @param frame buffer with sound in 16 bit mono PCM 16000 format
     * @param len   len of data
     * @return not null if successful
     */
    public native int writeFrame(ByteBuffer frame, int len);
```
I think this function is critical. The reason why param FRAME is limited to 16 bit mono PCM 16000 format  is out of the consideration of this issue we are talking about.

You might need to write a new native function that could encoder audio frame in a more extensive range.

Sorry that I can only help you so far. Good luck!

**Comment by silent10** [comment]
I am still struggling with this. Can you help me in removing the limitation of 16 bit mono PCM 16000 on param Frame?  Opus supports 8000, 12000, 16000, 24000 and 48000 sampling rates.

**Comment by louisyonge** [comment]
@silent10 
Hi, Silent10. I am sorry that I can ONLY provide some information that might be helpful for you

You know, this project is based on three open source project, opus-codec, opus-file, and opus-tools.
<http://opus-codec.org/development/> Opus tool could convert WAV file to almost every types of Opus. Maybe, the difference between recording an opus file and converting a WAV to opus, is that the former is a dynamic stream, while the latter is a static stream. But the minimum operation unit of the two are the same -- frame. Thus, " public native int writeFrame(ByteBuffer frame, int len);" is the key. What's more, you might need to pay attention to how the opus is initialized.
